Update backup
Added safety checks to make sure root partition is read-only and overlay is active before proceeding.

diff --git a/misc/backup b/misc/backup
--- a/misc/backup
+++ b/misc/backup
@@ -22,6 +22,13 @@ elif [[ ! "${DEV}" =~ /dev/mmcblk* ]]; then
 	umount ${DEV}* >& /dev/null
 else
 	SRCH=${DEV/p1/p2}
+	if [[ ! "$(mount | grep ${SRCH} | awk '{print $3}')" == "/ro" ]]; then
+		echo -e "${RED}ERROR:${NC} Cannot backup root partition without overlay active.  Aborting!"
+		exit 1
+	else if [[ "$(mount | grep ${SRCH} | awk '{print $3" "$6}')" =~ rw ]]; then
+		echo -e "${RED}ERROR:${NC} Root partition must be read-only in order to backup.  Aborting!"
+		exit 1
+	fi
 	DEV=${DEV/p1/}
 fi
 END=$(( $(sudo fdisk --list ${DEV} | grep "${SRCH}" | awk '{print $3}') + 1 ))
