Update router-helper

diff --git a/files/usr/local/bin/router-helper b/files/usr/local/bin/router-helper
--- a/files/usr/local/bin/router-helper
+++ b/files/usr/local/bin/router-helper
@@ -86,7 +86,7 @@ function askYesNo {
 check_ro
 RO_DEV=$(cat /ro/etc/fstab | grep " / " | sed "s|^#||g" | cut -d" " -f 1)
 case $1 in
-	chroot_ro|chroot-ro)
+	chroot)
 		remount_rw
 		echo "CHROOT" > /tmp/debian_chroot
 		chattr +i /tmp/debian_chroot
@@ -96,19 +96,59 @@ case $1 in
 		remount_ro
 		;;
 
-	remount_rw|remount-rw)
-		remount_rw notrap
+	remount)
+		if [[ "$2" == "rw" ]]; then
+			remount_rw notrap
+		elif [[ "$2" == "ro" ]]; then
+			remount_ro
+		else
+			echo "SYNTAX: $(basename $0) remount [ro|rw]"
+		fi
 		;;
 		
-	remount_ro|remount-ro)
-		remount_ro
-		;;
-
 	reformat)
+		if [[ ! -z "$2" && ! "$2" =~ -(y|-yes) ]]; then
+			echo "SYNTAX: $(basename $0) reformat [-y|--yes]"
+			exit 1
+		fi
+		if [[ ! "$2" =~ -(y|-yes) ]]; then
+			echo "WARNING: Persistent storage will be formatted.  This action cannot be undone!\n\n"
+			askYesNo "Are you SURE you want to do this?" || exit 0
+		fi
 		remount_rw
 		sed -i "s|^SECONDARY_REFORMAT=.*|SECONDARY_REFORMAT=yes|g" /ro/etc/overlayRoot.conf
 		remount_ro
 		reboot now
+		;;
+
+	overlay)
+		if [[ "$2" == "enable" ]]; then
+			if cat /boot/bananapi/bpi-r2/linux/uEnv.txt | grep "init=/sbin/overlayRoot.sh noOverlayRoot" >& /dev/null; then
+				echo "INFO: Overlay root filesystem script already enabled!"
+			else
+				sed -i "s|init=/sbin/overlayRoot.sh|init=/sbin/overlayRoot.sh noOverlayRoot|g" /boot/bananapi/bpi-r2/linux/uEnv.txt
+				if ! cat /boot/bananapi/bpi-r2/linux/uEnv.txt | grep "init=/sbin/overlayRoot.sh noOverlayRoot" >& /dev/null; then
+					echo "ERROR: Unable to enable Overlay Root script!"
+					exit 1
+				else
+					echo "Overlay Root script enabled for next reboot!"
+				fi
+			fi
+		elif [[ "$2" == "disable" ]]; then
+			if ! cat /boot/bananapi/bpi-r2/linux/uEnv.txt | grep "init=/sbin/overlayRoot.sh noOverlayRoot" >& /dev/null; then
+				echo "INFO: Overlay root filesystem script already disabled!"
+			else
+				sed -i "s|init=/sbin/overlayRoot.sh noOverlayRoot|init=/sbin/overlayRoot.sh|g" /boot/bananapi/bpi-r2/linux/uEnv.txt
+				if cat /boot/bananapi/bpi-r2/linux/uEnv.txt | grep "init=/sbin/overlayRoot.sh noOverlayRoot" >& /dev/null; then
+					echo "ERROR: Unable to disable Overlay Root script!"
+					exit 1
+				else
+					echo "Overlay Root script disabled for next reboot!"
+				fi
+			fi
+		else
+			echo "SYNTAX: $(basename $0) overlay [enable|disable]"
+		fi
 		;;
 
 	*)
